language: php
php: '5.6'
before_install:
  -  openssl aes-256-cbc -K $encrypted_6460f3d9e51f_key -iv $encrypted_6460f3d9e51f_iv -in credentials-dreamteam.json.enc -out credentials-dreamteam.json -d
  
before_script: php composer.phar install

deploy:
  provider: gae
  keyfile: credentials-dreamteam.json
  project: fhi-wawd-dreamteam
  config: app.yaml
